In [1]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import ElementClickInterceptedException, NoSuchElementException, StaleElementReferenceException, ElementNotInteractableException
import time
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia Url=https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videosYou need to find following details:A) Rank B) NameC) ArtistD) Upload date E) Views

In [2]:
driver=webdriver.Chrome('chromedriver.exe')
driver.maximize_window()
url=("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
driver.get(url)
time.sleep(2)

In [3]:
Rank= []
Name= []
Artist= []
Upload_date= []             
Views= []

#scraping Rank
try:
    Rank_tag= driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[1]")
    for i in Rank_tag:
        Rank.append(i.text)
except NoSuchElementException as e:
    Rank.append("--")

#scraping Name
try:
    Name_tag= driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[2]")
    for i in Name_tag:
        Name.append(i.text.split('[')[0])
except NoSuchElementException as e:
    Name.append("--") 

#scraping Artist
try:
    Artist_tag= driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[3]")
    for i in Artist_tag:
        Artist.append(i.text)
except NoSuchElementException as e:
    Artist.append("--")

#scraping Upload date
try:
    Upload_tag= driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[5]")
    for i in Upload_tag:
        Upload_date.append(i.text)
except NoSuchElementException as e:
    Upload_date.append("--")

#Scraping views
try:
    View_tag= driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter']/tbody/tr/td[4]")
    for i in View_tag:
        Views.append(i.text)
except NoSuchElementException as e:
    Views.append("--")
    
#printing length
print(len(Rank),len(Name),len(Artist),len(Upload_date),len(Views))

#creating DataFrame
viewed_videos=pd.DataFrame({"Rank":Rank,"Name":Name,"Artist":Artist,"Upload_date":Upload_date,"Views":Views})
viewed_videos

49 49 49 49 49

,Rank,Name,Artist,Upload_date,Views
0,1.,"""Baby Shark Dance""",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.27
1,2.,"""Despacito""",Luis Fonsi,"January 12, 2017",8.08
2,3.,"""Johny Johny Yes Papa""",LooLoo Kids,"October 8, 2016",6.61
3,4.,"""Bath Song""",Cocomelon – Nursery Rhymes,"May 2, 2018",6.01
4,5.,"""Shape of You""",Ed Sheeran,"January 30, 2017",5.91
5,6.,"""See You Again""",Wiz Khalifa,"April 6, 2015",5.78
6,7.,"""Phonics Song with Two Words""",ChuChu TV,"March 6, 2014",5.15
7,8.,"""Wheels on the Bus""",Cocomelon – Nursery Rhymes,"May 24, 2018",4.92
8,9.,"""Uptown Funk""",Mark Ronson,"November 19, 2014",4.83
9,10.,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,"February 27, 2018",4.81
10,11.,"""Gangnam Style""",Psy,"July 15, 2012",4.69
11,12.,"""Masha and the Bear – Recipe for Disaster""",Get Movies,"January 31, 2012",4.53
12,13.,"""Dame Tu Cosita""",El Chombo,"April 5, 2018",4.23
13,14.,"""Sugar""",Maroon 5,"January 14, 2015",3.82
14,15.,"""Axel F""",Crazy Frog,"June 16, 2009",3.75
15,16.,"""Roar""",Katy Perry,"September 5, 2013",3.73
16,17.,"""Counting Stars""",OneRepublic,"May 31, 2013",3.72
17,18.,"""Sorry""",Justin Bieber,"October 22, 2015",3.63
18,19.,"""Thinking Out Loud""",Ed Sheeran,"October 7, 2014",3.55
19,20.,"""Baa Baa Black Sheep""",Cocomelon – Nursery Rhymes,"June 25, 2018",3.49
20,21.,"""Waka Waka (This Time for Africa)""",Shakira,"June 4, 2010",3.47
21,22.,"""Dark Horse""",Katy Perry,"February 20, 2014",3.45
22,23.,"""Faded""",Alan Walker,"December 3, 2015",3.40
23,24.,"""Let Her Go""",Passenger,"July 25, 2012",3.38
24,25.,"""Girls Like You""",Maroon 5,"May 31, 2018",3.37
25,26.,"""Perfect""",Ed Sheeran,"November 9, 2017",3.37
26,27.,"""Bailando""",Enrique Iglesias,"April 11, 2014",3.33
27,28.,"""Lean On""",Major Lazer,"March 22, 2015",3.33
28,29.,"""Humpty the train on a fruits ride""",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.30
29,30.,"""Lakdi Ki Kathi""",Jingle Toons,"June 14, 2018",3.30
30,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,"7,046,700,000","November 2, 2020","June 17, 2016"
31,"""Despacito""[7]",Luis Fonsi,"2,993,700,000","August 4, 2017","January 12, 2017"
32,"""See You Again""[18]",Wiz Khalifa,"2,894,000,000","July 10, 2017","April 6, 2015"
33,"""Gangnam Style""⁂[27]",Psy,"803,700,000","November 24, 2012","July 15, 2012"
34,"""Baby""*[63]",Justin Bieber,"245,400,000","July 16, 2010","February 19, 2010"
35,"""Bad Romance""[67]",Lady Gaga,"178,400,000","April 14, 2010","November 24, 2009"
36,"""Charlie Bit My Finger""‡[71]",HDCYT,"128,900,000","October 25, 2009","May 22, 2007"
37,"""Evolution of Dance""[74]",Judson Laipply,"118,900,000","May 2, 2009","April 6, 2006"
38,"""Girlfriend""‡[76][77]",RCA Records,"92,600,000","July 17, 2008","February 27, 2007"
39,"""Evolution of Dance""[74]",Judson Laipply,"78,400,000","March 15, 2008","April 6, 2006"
40,"""Music Is My Hot Hot Sex""‡[81]",CLARUSBARTEL72,"76,600,000","March 1, 2008","April 9, 2007"
41,"""Evolution of Dance""*[74]",Judson Laipply,"10,600,000","May 19, 2006","April 6, 2006"
42,"""Pokémon Theme Music Video""‡[87]",Smosh,"4,300,000","March 12, 2006","November 28, 2005"
43,"""Myspace – The Movie""‡[92][93]",eggtea,"2,700,000","February 18, 2006","January 31, 2006"
44,"""Phony Photo Booth""‡[96]",mugenized,"3,400,000","January 21, 2006","December 1, 2005"
45,"""The Chronic of Narnia Rap""‡[98]",youtubedude,"2,300,000","January 9, 2006","December 18, 2005"
46,"""Ronaldinho: Touch of Gold""‡*[100]",Nikesoccer,"255,000","October 31, 2005","October 21, 2005"
47,"""I/O Brush""‡*[103]",larfus,"247,000","October 29, 2005","October 5, 2005"
48,"""Me at the zoo""[105]",jawed,1,"April 23, 2005","April 23, 2005"

# 2. Scrape the details team India’s internationalfixtures from bcci.tv. Url=https://www.bcci.tv/.  You need to find following details: A) Match title (I.e. 1stODI) B) Series C) Place D) Date E) TimeNote: - From bcci.tv home page you have reach to the international fixture page through code.

In [4]:
driver_2=webdriver.Chrome('chromedriver.exe')
driver_2.maximize_window()
url=("https://www.bcci.tv/")
driver_2.get(url)
time.sleep(2)

In [5]:
button= driver_2.find_element(By.XPATH,'//span[@class = "menu-icon__line menu-icon__line-right"]').get_attribute('href')

In [6]:
#selecting International
International= driver_2.find_element(By.XPATH,'//a[@class = "nav-link "]').click()

In [7]:
#clicking on dropdown
Select= driver_2.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div[3]/div/div[1]').click()

In [8]:
#selecting ODI
OdI= driver_2.find_element(By.XPATH,'/html/body/div[2]/div[2]/div/div/div/div[2]/div[2]/div/div[3]/div/div[2]/div[3]').click()

In [9]:
Match_title= []
Series= []
Place= []
Date= []
Time= []

#scraping Match Title
try:
    Match_title_tag= driver_2.find_elements(By.XPATH,"//div[@class='fixture-card-top']/h5[2]")
    for i in Match_title_tag:
        Match_title.append(i.text)
except NoSuchElementException as e:
    Match_title.append("--")

#scraping Series
try:
    Series_tag= driver_2.find_elements(By.XPATH,"//div[@class='fixture-card-bottom']")
    for i in Series_tag:
        Series.append(i.text.split("-")[0])
except NoSuchElementException as e:
    Series.append("--")
    
#scraping Place
try:
    Place_tag= driver_2.find_elements(By.XPATH,"//div[@class='fixture-card-bottom']")
    for i in Place_tag:
        Place.append(i.text.split("-")[1].replace("\n",","))
except NoSuchElementException as e:
    Place.append("--") 

#scraping Date
try:
    Date_tag= driver_2.find_elements(By.XPATH,"//div[@class='match-card-left match-schedule']")
    for i in Date_tag:
        Date.append(i.text)
except NoSuchElementException as e:
    Date.append("--")

#scraping Time   
try:
    Time_tag= driver_2.find_elements(By.XPATH,"//div[@class='match-card-right match-schedule ']")
    for i in Time_tag:
        Time.append(i.text)
except NoSuchElementException as e:
    Time.append("--")

#printing length
print(len(Match_title),len(Series),len(Place),len(Date),len(Time))

#creating Dataframe
international_fixtures=pd.DataFrame({"Match_title":Match_title,"Series":Series,"Place":Place,"Date":Date,"Time":Time})
international_fixtures

3 3 3 3 3

,Match_title,Series,Place,Date,Time
0,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,1st ODI,"Wankhede Stadium, Mumbai,Match Centre",17 MAR 2023,1:30 PM IST
1,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,2nd ODI,Dr YS Rajasekhara Reddy ACA,19 MAR 2023,1:30 PM IST
2,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,3rd ODI,"MA Chidambaram Stadium, Chennai,Match Centre",22 MAR 2023,1:30 PM IST

In [10]:
driver_2.close()

# 3. Scrape the details of State-wise GDP ofIndia fromstatisticstime.com. Url=http://statisticstimes.com/You have to find following details:A) Rank          B) State C) GSDP(18-19)- at current prices D) GSDP(19-20)- at current prices    E) Share(18-19) F) GDP($ billion) Note: - From statisticstimes home page you have to reach to economy page through code

In [11]:
driver_4=webdriver.Chrome('chromedriver.exe')
driver_4.maximize_window()
url=("https://www.statisticstimes.com/")
driver_4.get(url)
time.sleep(2)

In [12]:
economy = driver_4.find_element(By.XPATH,"//*[@id='top']/div[2]/div[2]/button")
try:
    economy.click()
except ElementNotInteractableException:
    driver_4.get(economy.get_attribute('href'))

In [14]:
gdp = driver_4.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[1]/h1").click()

In [15]:
Rank= []
State= []
GSDP_2019= []
GSDP_2018= []
Share_2017= []
GDP= []

#scraping Rank
try:
    Rank_tag=driver_4.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[1]")
    for i in Rank_tag:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('-')
except StaleElementReferenceException:
    Rank.append('--')

#scraping State
try:
    State_tag=driver_4.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[2]")
    for i in State_tag:
        State.append(i.text)
except NoSuchElementException:
    State.append('-')
except StaleElementReferenceException:
    State.append('--')

#scraping GSDP 2019
try:
    GSDP_2019_tag=driver_4.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[3]")
    for i in GSDP_2019_tag:
        GSDP_2019.append(i.text)
except NoSuchElementException:
    GSDP_2019.append('-')
except StaleElementReferenceException:
    GSDP_2019.append('--')
    
#scraping GSDP 2018
try:
    GSDP_2018_tag=driver_4.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[4]")
    for i in GSDP_2018_tag:
        GSDP_2018.append(i.text)
except NoSuchElementException:
    GSDP_2018.append('-')
except StaleElementReferenceException:
    GSDP_2018.append('--')
    
#scraping share 2017
try:
    Share_2017_tag=driver_4.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[5]")
    for i in Share_2017_tag:
        Share_2017.append(i.text)
except NoSuchElementException:
    Share_2017.append('-')
except StaleElementReferenceException:
    Share_2017.append('--')

#scraping GDP
try:
    GDP_tag=driver_4.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[6]")
    for i in GDP_tag:
        GDP.append(i.text)
except NoSuchElementException:
    GDP.append('-')
except StaleElementReferenceException:
    GDP.append('--')
    
#printing length
print(len(Rank),len(State),len(GSDP_2019),len(GSDP_2018),len(Share_2017),len(GDP))

#creating Dataframe
State_GDP=pd.DataFrame({"Rank":Rank,"State":State,"GSDP_2019":GSDP_2019,"GSDP_2018":GSDP_2018,"Share_2017":Share_2017,"GDP":GDP}).set_index('Rank')
State_GDP

0 0 0 0 0 0

Empty DataFrame
Columns: [State, GSDP_2019, GSDP_2018, Share_2017, GDP]
Index: []

# 4. Scrape the details of trending repositories on Github.com. Url=https://github.com/You have to find the following details: A) Repository title B) Repository description C) Contributors count D) Language used

In [13]:
driver_5=webdriver.Chrome('chromedriver.exe')
driver_5.maximize_window()
url=(" https://github.com/")
driver_5.get(url)
time.sleep(2)

In [14]:
# Clicking on explore sub menu
explore = driver_5.find_element(By.XPATH,'//li[@class = "mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"][4]')
try:
    explore.click()
    time.sleep(5)
except ElementNotInteractableException:
    driver_5.get(explore.get_attribute('href'))

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//li[@class = "mr-0 mr-lg-3 position-relative flex-wrap flex-justify-between flex-items-center border-bottom border-lg-bottom-0 d-block d-lg-flex flex-lg-nowrap flex-lg-items-center"][4]"}
  (Session info: chrome=110.0.5481.78)
Stacktrace:
Backtrace:
	(No symbol) [0x00C037D3]
	(No symbol) [0x00B98B81]
	(No symbol) [0x00A9B36D]
	(No symbol) [0x00ACD382]
	(No symbol) [0x00ACD4BB]
	(No symbol) [0x00B03302]
	(No symbol) [0x00AEB464]
	(No symbol) [0x00B01215]
	(No symbol) [0x00AEB216]
	(No symbol) [0x00AC0D97]
	(No symbol) [0x00AC253D]
	GetHandleVerifier [0x00E7ABF2+2510930]
	GetHandleVerifier [0x00EA8EC1+2700065]
	GetHandleVerifier [0x00EAC86C+2714828]
	GetHandleVerifier [0x00CB3480+645344]
	(No symbol) [0x00BA0FD2]
	(No symbol) [0x00BA6C68]
	(No symbol) [0x00BA6D4B]
	(No symbol) [0x00BB0D6B]
	BaseThreadInitThunk [0x76B36BD9+25]
	RtlGetFullPathName_UEx [0x77C98FD2+1218]
	RtlGetFullPathName_UEx [0x77C98F9D+1165]

# 5. Scrape the details of top 100 songs on billiboard.com. Url=https:/www.billboard.com/  You have to find the following details: A) Song name B) Artist name C) Last week rank D) Peak rank E) Weeks on board Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [27]:
driver=webdriver.Chrome('chromedriver.exe')
url=("https://www.billboard.com")
driver.get(url)
time.sleep(2)

In [29]:
menu = driver.find_element(By.XPATH,"/html/body/div[3]/main/div[2]/div[1]/div[1]/div[1]/div[2]/header/h2").click()

In [31]:
menu = driver.find_element(By.XPATH,"/html/body/div[3]/main/div[2]/div[1]/div[1]/div[1]/div[2]/div/div[1]/div/div[1]/div[2]/div").click()

In [32]:
Name=[]
Artist=[]
rank=[]

#Scraping name
Name_tag=driver.find_elements(By.XPATH,"//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet']")
for i in Name_tag:
    Name.append(i.text)

#Scraping artist
Artist_tag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']")
for i in Artist_tag:
    Artist.append(i.text)

#Scraping rank
rankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")
for i in rankTag[:3]:
    rank.append(i.text )

In [33]:
#Scraping name
Rank=[]
nameTag=driver.find_elements(By.XPATH,"//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only']")
for i in nameTag:
    Name.append(i.text )

#Scraping artist
artistTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
for i in artistTag:
    Artist.append(i.text )

#Scraping rank
RankTag=driver.find_elements(By.XPATH,"//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")
for i in RankTag:
    Rank.append(i.text)

In [34]:
# removing ''
for i in Rank:
    if i=='':
        Rank.remove(i)

In [37]:
# slicing Data
last_week_rank=Rank[0::3]
last_week_rank.insert(0,rank[0])
peak_rank=Rank[1::3]
peak_rank.insert(0,rank[1])
weeks_on_board=Rank[2::3]
weeks_on_board.insert(0,rank[2])

IndexError: list index out of range

In [ ]:
# Create Dataframe
songs_top=pd.DataFrame({"Name":Name[:100],"Artist":Artist[:100],"Last Week Rank":last_week_rank[0:100],"Peak Rank":peak_rank[0:100],"Weeks On Board":weeks_on_board[0:100]})
songs_top

# 6.  Scrape the details of Highest sellingnovels.Url= https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/You have to find the following details: A) Book name  B) Author name C) Volumes sold D) Publisher E) Genre

In [9]:
driver_8=webdriver.Chrome('chromedriver.exe')
driver_8.maximize_window()
url=("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")
driver_8.get(url)
time.sleep(2)

In [10]:
Books=[]
Genre=[]

#scraping novels
try:
    Books_tag=driver_8.find_elements(By.XPATH,"//td[@class='left']")
    for i in Books_tag:
        Books.append(i.text)
except:
    Books.append("-")
    
#scraping novel's genre
try:
    Genre_tag=driver_8.find_elements(By.XPATH,"//td[@class='last left']")
    for i in Genre_tag:
        Genre.append(i.text)
except:
    Genre.append("-")

In [11]:
#slicing novels data
Book_name=Books[1::5]
Author_name=Books[2::5]
Volumes_sold=Books[3::5]
Publisher=Books[4::5]

In [12]:
#printing length
print(len(Book_name), len(Author_name),len(Volumes_sold), len(Publisher), len(Genre))

100 100 100 100 100

In [13]:
#creating Dataframe
novels=pd.DataFrame({"Book Name":Book_name,"Author Name":Author_name,"Volumes Sold":Volumes_sold,"Publisher":Publisher,"Genre":Genre})
novels

,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 7. Scrape the details most watched tv series of all time from imdb.com.        Url = https://www.imdb.com/list/ls095964455/ You have to find the following details: A) Name B) Year span C) Genre D) Run time E) Ratings F) Votes

In [14]:
driver_9=webdriver.Chrome('chromedriver.exe')
driver_9.maximize_window()
url=("http://www.imdb.com/list/ls095964455/")
driver_9.get(url)
time.sleep(2)

In [15]:
Name= []
Year_span= []
Genre= []
Run_time= []
Ratings= []
Votes= []

#scraping series name
try:
    Name_tag= driver_9.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a")
    for i in Name_tag:
        Name.append(i.text)
except NoSuchElementException as e:
    Name.append("--")

#scraping series Year span
try:
    Year_span_tag= driver_9.find_elements(By.XPATH,"//span[@class='lister-item-year text-muted unbold']")
    for i in Year_span_tag:
        Year_span.append(i.text)
except NoSuchElementException as e:
    Year_span.append("--") 
    
#scraping series Genre
try:
    Genre_tag= driver_9.find_elements(By.XPATH,"//span[@class='genre']")
    for i in Genre_tag:
        Genre.append(i.text)
except NoSuchElementException as e:
    Genre.append("--")
    
#scraping series Run Time
try:
    Run_time_tag= driver_9.find_elements(By.XPATH,"//span[@class='runtime']")
    for i in Run_time_tag:
        Run_time.append(i.text)
except NoSuchElementException as e:
    Run_time.append("--")
    
#scraping series Ratings
try:
    Ratings_tag= driver_9.find_elements(By.XPATH,"//span[@class='ipl-rating-star__rating']")
    for i in Ratings_tag[::23]:
        Ratings.append(i.text)
except NoSuchElementException as e:
    Ratings.append("--")
    
#scraping series Votes
try:
    Votes_tag= driver_9.find_elements(By.XPATH,"//span[@name='nv']")
    for i in Votes_tag:
        Votes.append(i.text)
except NoSuchElementException as e:
    Votes.append("--")
    
#printing length
print(len(Name), len(Year_span), len(Genre), len(Run_time), len(Ratings), len(Votes))

100 100 100 100 100 100

In [16]:
#creating Dataframe
tv_series= pd.DataFrame({"Name":Name[:100],"Year span":Year_span[:100],"Genre":Genre[:100],"Run time":Run_time[:100],"Ratings":Ratings[:100],"Votes":Votes[:100]})
tv_series

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,123,499"
1,Stranger Things,(2016–2024),"Drama, Fantasy, Horror",51 min,8.7,"1,211,359"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,007,181"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"297,163"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"256,102"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,741"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"62,628"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"202,999"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"42,051"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"250,829"

# 8. Details of Datasets from UCI machine learning repositories.                       Url = https://archive.ics.uci.edu/ You have to find the following details:              A) Dataset name B) Data type C) Task D) Attribute type E) No of instances        F) No of attribute G) YearNote: - from the home page you have to go to the ShowAllDataset page through code

In [2]:
driver_0=webdriver.Chrome('chromedriver.exe')
driver_0.maximize_window()
url=("https://archive.ics.uci.edu/")
driver_0.get(url)
time.sleep(2)

In [3]:
#clicking on view all Dataset
Dataset= driver_0.find_elements(By.XPATH,"//span[@class='normal']/b/a")[0].get_attribute('href')
driver_0.get(Dataset)

In [4]:
# Scraping dataset
data=[]
try:
    data_tag=driver_0.find_elements(By.XPATH,"//td//p[@class='normal']")
    for i in data_tag[8:4362]:
        data.append(i.text )
except:
    data.append('-')

In [5]:
#slicing dataset
Dataset_name=data[::7]
Data_type=data[1::7]
Task=data[2::7]
Attribute_type=data[3::7]
instances=data[4::7]
attribute=data[5::7]
Year=data[6::7]

In [6]:
#printing length
print(len(Dataset_name), len(Data_type), len(Task), len(Attribute_type), len(instances), len(attribute), len(Year))

622 622 622 622 622 622 622

In [7]:
#creating Dataframe
Datasets= pd.DataFrame({"Dataset name":Dataset_name,"Data type":Data_type,"Task":Task,"Attribute type":Attribute_type,"Instances":instances,"Attribute":attribute,"Year":Year})
Datasets

,Dataset name,Data type,Task,Attribute type,Instances,Attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021